### ISSUE TITLE
What am I doing wrong here?

### ISSUE THREAD

**Issue by isGabe** [jonathanstark/FastActive#7]
I'm excited to use FastActive, as I think it's just the right way to handle the tap/delay issue: simply.

So far though when I try to implement it, the `active` class gets added to an `a` element, but it stays there pretty much for good. It will sometimes get removed on subsequent taps/touches, but it's random.

I expected the `active` class to only remain while the link was being touched. Is that a correct assumption?

I've been testing this on my iPhone 4S/iOS7/Safari, Chrome.

Example: http://codepen.io/FStop/pen/cuokl

Full pen link for easier mobile access: http://codepen.io/FStop/full/cuokl

I've also tested in Codepen's "debug" mode, which takes it out of an iframe and makes it into a plain old web page, just in case that had anything to do with it. Doesn't make a difference.

Am I an idiot (separate question, really) and missing something simple in the setup?

**Comment by jonathanstark** [comment]
The expected behavior is for the active class to stay until the user moves finger or touches somewhere else. The base usecase is that the user clicks a link, the link stay highlighted until the new page loads. 

If the link that you're highlighting doesn't navigate to a new page you want to remove the active class in the oncomplete callback of whatever action you're taking.

**Comment by isGabe** [comment]
OK, that makes sense. My first crack at using this was on a mobile menu show/hide trigger rather than a traditional link. I'll experiment more with your clarifications, which are very helpful. Thanks for taking the time to share this and to respond to my dumb question.
